/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jagatnasakar
 */
 

import java.io.*;

import javax.swing.table.DefaultTableModel;
import java.util.Date; 
import java.text.SimpleDateFormat; 
import java.sql.*;
import Project.ConnectionProvider;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
public class Billing extends javax.swing.JFrame { //crete new form "Billing"
    public int finalTotal = 0;
    public Billing() {
        initComponents();
        
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
        Date d = new Date();  
        DAte.setText(formatter.format(d));
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now=LocalDateTime.now();
        TTime.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DAte = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TTime = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BContact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BEmail = new javax.swing.JTextField();
        BAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PNamek = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PId = new javax.swing.JTextField();
        PName = new javax.swing.JTextField();
        PDescription = new javax.swing.JTextField();
        PRate = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        PQuantity = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TOtal = new javax.swing.JTextField();
        PAid = new javax.swing.JTextField();
        REturn = new javax.swing.JTextField();
        SAve = new javax.swing.JButton();
        REset = new javax.swing.JButton();
        CLose = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Billing icon.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        jLabel2.setText("Billing ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 5, -1, -1));

        jLabel3.setText("Date : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 17, -1, -1));

        DAte.setText("jLabel4");
        getContentPane().add(DAte, new org.netbeans.lib.awtextra.AbsoluteConstraints(1046, 17, -1, -1));

        jLabel5.setText("Time : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 51, -1, -1));

        TTime.setText("jLabel6");
        getContentPane().add(TTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1046, 51, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 1152, -1));

        jLabel7.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        jLabel7.setText("Buyer Details : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 102, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setText("Name : ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 136, -1, -1));

        BName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNameActionPerformed(evt);
            }
        });
        getContentPane().add(BName, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 132, 180, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("Contact : ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 136, -1, -1));

        BContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BContactActionPerformed(evt);
            }
        });
        getContentPane().add(BContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 132, 195, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setText("Email : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 136, -1, -1));

        BEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEmailActionPerformed(evt);
            }
        });
        getContentPane().add(BEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 132, 212, -1));

        BAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddressActionPerformed(evt);
            }
        });
        getContentPane().add(BAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 132, 204, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("Address : ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 136, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 164, 1114, -1));

        jLabel12.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        jLabel12.setText("Product Details : ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 188, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel13.setText("Product ID : ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 236, -1, -1));

        PNamek.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PNamek.setText("Name : ");
        getContentPane().add(PNamek, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 230, -1, 28));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel16.setText("Rate :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 236, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel17.setText("Description : ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 236, -1, -1));

        PId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIdActionPerformed(evt);
            }
        });
        getContentPane().add(PId, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 232, 124, -1));

        PName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNameActionPerformed(evt);
            }
        });
        getContentPane().add(PName, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 232, 157, -1));
        getContentPane().add(PDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 232, 163, -1));
        getContentPane().add(PRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 232, 111, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 316, 1152, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel18.setText("Quantity : ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 236, -1, -1));
        getContentPane().add(PQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 232, 128, -1));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 270, 101, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 334, 559, 186));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel14.setText("Calculation Details ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 334, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel15.setText("Total : ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 393, -1, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel19.setText("Paid Rs :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 437, -1, -1));

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel20.setText("Return Rs : ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 494, -1, -1));
        getContentPane().add(TOtal, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 381, 144, 24));

        PAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAidActionPerformed(evt);
            }
        });
        getContentPane().add(PAid, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 425, 144, 24));
        getContentPane().add(REturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 494, 144, -1));

        SAve.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        SAve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        SAve.setText("Save");
        SAve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAveActionPerformed(evt);
            }
        });
        getContentPane().add(SAve, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 374, -1, -1));

        REset.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        REset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        REset.setText("Reset");
        REset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REsetActionPerformed(evt);
            }
        });
        getContentPane().add(REset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 418, -1, -1));

        CLose.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        CLose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/closee.png"))); // NOI18N
        CLose.setText("Close");
        CLose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLoseActionPerformed(evt);
            }
        });
        getContentPane().add(CLose, new org.netbeans.lib.awtextra.AbsoluteConstraints(992, 472, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back2.jpeg"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 650, 570));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back2.jpeg"))); // NOI18N
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -10, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNameActionPerformed
        String name = BName.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from buyer where name like '"+name+"%'");
            if(rs.next())
            {
                BName.setText(rs.getString(1));
                BContact.setText(rs.getString(4));
                BEmail.setText(rs.getString(3));
                BAddress.setText(rs.getString(5));
                
            }
            else
            {
                BContact.setText("");
                BEmail.setText("");
                BAddress.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BNameActionPerformed

    private void BContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BContactActionPerformed
        String contact = BContact.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from buyer where contactNo like '"+contact+"%'");
            if(rs.next())
            {
                BName.setText(rs.getString(1));
                BContact.setText(rs.getString(4));
                BEmail.setText(rs.getString(3));
                BAddress.setText(rs.getString(5));
                
            }
            else
            {
                BName.setText("");
                BEmail.setText("");
                BAddress.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BContactActionPerformed

    private void BEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEmailActionPerformed
        String email = BEmail.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from buyer where email like '"+email+"%'");
            if(rs.next())
            {
                BName.setText(rs.getString(1));
                BContact.setText(rs.getString(4));
                BEmail.setText(rs.getString(3));
                BAddress.setText(rs.getString(5));
                
            }
            else
            {
                BContact.setText("");
                BName.setText("");
                BAddress.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BEmailActionPerformed

    private void BAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddressActionPerformed
        String address = BAddress.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from buyer where address like '"+address+"%'");
            if(rs.next())
            {
                BName.setText(rs.getString(1));
                BContact.setText(rs.getString(4));
                BEmail.setText(rs.getString(3));
                BAddress.setText(rs.getString(5));
                
            }
            else
            {
                BName.setText("");
                BEmail.setText("");
                BContact.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BAddressActionPerformed

    private void PIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIdActionPerformed
        String id = PId.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from product where pid='"+id+"'");
            if(rs.next())
            {
                PName.setText(rs.getString(2));
                PQuantity.setText("1");
                PRate.setText(rs.getString(3));
                PDescription.setText(rs.getString(4));
                
            }
            else
            {
                PName.setText("");
                PRate.setText("");
                PQuantity.setText("");
                PDescription.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_PIdActionPerformed

    private void PNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNameActionPerformed
        String name = PName.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from product where pname='"+name+"'");
            if(rs.next())
            {
                PId.setText(rs.getString(1));
                PQuantity.setText("1");
                PRate.setText(rs.getString(3));
                PDescription.setText(rs.getString(4));
                
            }
            else
            {
                PId.setText("");
                PRate.setText("");
                PQuantity.setText("");
                PDescription.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_PNameActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        int price =Integer.parseInt(PRate.getText());
        int quantity = Integer.parseInt(PQuantity.getText());
        int total = price*quantity;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();  //defaultTableModel construct a table of 0 row and 0 column
        model.addRow(new Object[]{PName.getText(), PDescription.getText(), price, quantity, total});
        finalTotal +=total;
        String finalTotal1 = String.valueOf(finalTotal);
        TOtal.setText(finalTotal1);
        
    }//GEN-LAST:event_addActionPerformed

    private void PAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAidActionPerformed
        String paid= PAid.getText();
        int k=Integer.parseInt(paid);
        finalTotal = k-finalTotal;
        String finalTotal1=String.valueOf(finalTotal);
        REturn.setText(finalTotal1);
        REturn.setEditable(false);
    }//GEN-LAST:event_PAidActionPerformed

    private void CLoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLoseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CLoseActionPerformed

    private void REsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REsetActionPerformed
        setVisible(false);
        new Billing().setVisible(true);
    }//GEN-LAST:event_REsetActionPerformed

    private void SAveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAveActionPerformed
        String name = BName.getText();
        String contact = BContact.getText();
        String email = BEmail.getText();
        String address = BAddress.getText();
        String path = "/Users/jagatnasakar/Desktop/"; //Macintosh HD/Users/jagatnasakar/NetBeansProjects/JavaApplication1/PDF Bill\\   
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+name+" "+DAte.getText()+".pdf"));
            doc.open();
            Paragraph paragraph = new Paragraph("                                       Beyonds Cloud Private Limited                              Phone : +91 9831784435/ 9856748765  \n\n\n ");
            doc.add(paragraph);
            Paragraph paragraph2 = new Paragraph(" Date & Time"+DAte.getText()+" "+TTime.getText()+"\n Buyer Details : \n Name : "+name+"\n Contact No : "+contact+"\n Email : "+email+"\n Address : "+address+"\n\n");
            doc.add(paragraph2);
            PdfPTable tb1 = new PdfPTable(5);//column 5
            tb1.addCell("Name ");
            tb1.addCell("Description ");
            tb1.addCell("Rate ");
            tb1.addCell("Quantity ");
            tb1.addCell("Sub Total ");
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                String n = jTable1.getValueAt(i, 0).toString();
                String d = jTable1.getValueAt(i, 1).toString();
                String r = jTable1.getValueAt(i, 2).toString();
                String q = jTable1.getValueAt(i, 3).toString();
                String s = jTable1.getValueAt(i, 4).toString();
                tb1.addCell(n);
                tb1.addCell(d);
                tb1.addCell(r);
                tb1.addCell(q);
                tb1.addCell(s);
            }
            doc.add(tb1);
            Paragraph paragraph3 = new Paragraph("\nTotal : "+ TOtal.getText()+"\nPaid : "+PAid.getText()+"\n Return Amount : "+REturn.getText()+"\n\nThankyou for Shopping...\nPlease visit again");
            doc.add(paragraph3);
            JOptionPane.showMessageDialog(null, "Bill Generated");
            setVisible(true);
            new Billing().setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_SAveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BAddress;
    private javax.swing.JTextField BContact;
    private javax.swing.JTextField BEmail;
    private javax.swing.JTextField BName;
    private javax.swing.JButton CLose;
    private javax.swing.JLabel DAte;
    private javax.swing.JTextField PAid;
    private javax.swing.JTextField PDescription;
    private javax.swing.JTextField PId;
    private javax.swing.JTextField PName;
    private javax.swing.JLabel PNamek;
    private javax.swing.JTextField PQuantity;
    private javax.swing.JTextField PRate;
    private javax.swing.JButton REset;
    private javax.swing.JTextField REturn;
    private javax.swing.JButton SAve;
    private javax.swing.JTextField TOtal;
    private javax.swing.JLabel TTime;
    private javax.swing.JButton add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
