/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jagatnasakar
 */
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JOptionPane;
public class deleteBuyer extends javax.swing.JFrame {

    /**
     * Creates new form deleteBuyer
     */
    public deleteBuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Contact = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Name = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 48)); // NOI18N
        jLabel1.setText("Delete Buyer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 18, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 678, 10));

        Contact.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Contact.setText("Contact No : ");
        getContentPane().add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 120, -1, -1));
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 116, 212, -1));

        search.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 115, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 162, 678, 10));

        Name.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        Name.setText("Name : ");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 194, -1, -1));

        Email.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        Email.setText("Email : ");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        Phone.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        Phone.setText("Contact No : ");
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        Gender.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        Gender.setText("Gender : ");
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        Address.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        Address.setText("Address : ");
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 191, 237, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 237, -1));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 237, -1));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 237, -1));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 237, -1));

        reset.setFont(new java.awt.Font("New Peninim MT", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, -1, -1));

        close.setFont(new java.awt.Font("New Peninim MT", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close2.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        delete.setFont(new java.awt.Font("New Peninim MT", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-64.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, 38));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 678, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounf.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -340, 700, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        setVisible(false);
        new deleteBuyer().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String ContactSearch = contact.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from buyer where contactNo='"+ContactSearch+"'");
            if(rs.next())
            {
                name.setText(rs.getString(1));
                phone.setText(rs.getString(2));
                email.setText(rs.getString(3));
                address.setText(rs.getString(4));
                gender.setText(rs.getString(5));
                contact.setEditable(false);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Details not available.");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                    
        }
    }//GEN-LAST:event_searchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String ContactSearch = contact.getText();
        int a= JOptionPane.showConfirmDialog(null, "Do you really want to delete ?", "select", JOptionPane.YES_NO_OPTION);
        if(a==0) //selected yes to delete
        {
            try{
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                st.executeUpdate("delete from buyer where contactNo='"+ContactSearch+"'");
                setVisible(false);
                new deleteBuyer().setVisible(true);
            }
            catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Phone;
    private javax.swing.JTextField address;
    private javax.swing.JButton close;
    private javax.swing.JTextField contact;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}