import java.awt.Color;
import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jagatnasakar
 */
public class newBuyer extends javax.swing.JFrame {

    /**
     * Creates new form newBuyer
     */
    public newBuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        emailTestfield = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        genderOption = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        resetButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/word-crop.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 33, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newBuyIcon.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 33, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newBuyIcon.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 33, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 720, -1));

        jLabel4.setText("Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 168, -1, -1));

        jLabel5.setText("Gender :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 219, -1, -1));

        jLabel6.setText("Email :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 271, -1, -1));

        jLabel7.setText("Contact No. : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 319, -1, -1));

        jLabel8.setText("Adress :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 365, -1, -1));

        nameTextField.setFont(new java.awt.Font("STIXIntegralsUpSm", 1, 14)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(204, 204, 204));
        nameTextField.setText("Enter your name...");
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 152, 296, -1));

        contactTextField.setFont(new java.awt.Font("STIXIntegralsUpSm", 1, 14)); // NOI18N
        contactTextField.setForeground(new java.awt.Color(204, 204, 204));
        contactTextField.setText("Enter your phone number....");
        contactTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactTextFieldFocusLost(evt);
            }
        });
        contactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 303, 296, -1));

        emailTestfield.setFont(new java.awt.Font("STIXIntegralsUpSm", 1, 14)); // NOI18N
        emailTestfield.setForeground(new java.awt.Color(204, 204, 204));
        emailTestfield.setText("Enter your email...");
        emailTestfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTestfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTestfieldFocusLost(evt);
            }
        });
        emailTestfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTestfieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTestfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 255, 296, -1));

        addressTextField.setFont(new java.awt.Font("STIXIntegralsUpSm", 1, 14)); // NOI18N
        addressTextField.setForeground(new java.awt.Color(204, 204, 204));
        addressTextField.setText("Enter your adress...");
        addressTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressTextFieldFocusLost(evt);
            }
        });
        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 349, 296, -1));

        genderOption.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        genderOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Others", "" }));
        genderOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderOptionActionPerformed(evt);
            }
        });
        getContentPane().add(genderOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 208, 296, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 387, 720, 10));

        resetButton.setFont(new java.awt.Font("Telugu Sangam MN", 1, 14)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 430, -1, -1));

        closeButton.setFont(new java.awt.Font("Telugu Sangam MN", 1, 14)); // NOI18N
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close2.png"))); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 431, -1, 34));

        saveButton.setFont(new java.awt.Font("Telugu Sangam MN", 1, 14)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formBackg.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 730, 490));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formBackg.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 720, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTextFieldActionPerformed
        
    }//GEN-LAST:event_contactTextFieldActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void emailTestfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTestfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTestfieldActionPerformed

    private void genderOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderOptionActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    
    
    //focus gained and lost
    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
        if(nameTextField.getText().equals("Enter your name..."))
        {
            nameTextField.setText("");
            nameTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
         if(nameTextField.getText().equals(""))
        {
            nameTextField.setText("Enter your name...");
            nameTextField.setForeground(new Color(153,153,153));  //grey color
        }
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void emailTestfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTestfieldFocusGained
        if(emailTestfield.getText().equals("Enter your email..."))
        {
            emailTestfield.setText("");
            emailTestfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_emailTestfieldFocusGained

    private void emailTestfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTestfieldFocusLost
         if(emailTestfield.getText().equals(""))
        {
            emailTestfield.setText("Enter your email...");
            emailTestfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_emailTestfieldFocusLost

    private void contactTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactTextFieldFocusGained
        if(contactTextField.getText().equals("Enter your phone number...."))
        {
            contactTextField.setText("");
            contactTextField.setForeground(new Color(0,0,0));   //text black
        }
    }//GEN-LAST:event_contactTextFieldFocusGained

    private void contactTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactTextFieldFocusLost
         if(contactTextField.getText().equals(""))
        {
            contactTextField.setText("Enter your phone number....");
            contactTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_contactTextFieldFocusLost

    private void addressTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTextFieldFocusGained
        if(addressTextField.getText().equals("Enter your adress..."))
        {
            addressTextField.setText("");
            addressTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_addressTextFieldFocusGained

    private void addressTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTextFieldFocusLost
        if(addressTextField.getText().equals(""))
        {
            addressTextField.setText("Enter your adress...");
            addressTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_addressTextFieldFocusLost

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);    
    }//GEN-LAST:event_closeButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        setVisible(false);
        new newBuyer().setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String name= nameTextField.getText();
        String contactNo = contactTextField.getText();
        String email = emailTestfield.getText();
        String address = addressTextField.getText();
        String gender = (String)genderOption.getSelectedItem();
        try{
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();
        st.executeUpdate("insert into buyer values('"+name+"', '"+gender+"', '"+email+"', '"+contactNo+"', '"+address+"')");
        JOptionPane.showMessageDialog(null, "Successfully Updated");
        setVisible(false);
        new newBuyer().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Mobile Number already registered...");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JTextField emailTestfield;
    private javax.swing.JComboBox<String> genderOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
