/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jagatnasakar
 */
import java.awt.Color;
import java.sql.*;
import Project.ConnectionProvider;

import javax.swing.JOptionPane;
public class newProduct extends javax.swing.JFrame {

    /**
     * Creates new form newProduct
     */
    public newProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Id = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Name = new javax.swing.JLabel();
        Rate = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        Activate = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        activate = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Menlo", 1, 48)); // NOI18N
        jLabel1.setText("New Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 8, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 594, -1));

        Id.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Id.setText("Product ID : ");
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 95, -1, -1));

        id.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        id.setForeground(new java.awt.Color(102, 102, 255));
        id.setText("400");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 95, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 600, -1));

        Name.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Name.setText("Name : ");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 160, -1, -1));

        Rate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Rate.setText("Rate : ");
        getContentPane().add(Rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 204, -1, -1));

        Description.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Description.setText("Description : ");
        getContentPane().add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 246, -1, -1));

        Activate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Activate.setText("Activate : ");
        getContentPane().add(Activate, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 289, -1, -1));

        name.setForeground(new java.awt.Color(153, 153, 153));
        name.setText("Enter Product name...");
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 156, 251, -1));

        rate.setForeground(new java.awt.Color(153, 153, 153));
        rate.setText("Enter the price...");
        rate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rateFocusLost(evt);
            }
        });
        getContentPane().add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 251, -1));

        description.setForeground(new java.awt.Color(153, 153, 153));
        description.setText("Add description...");
        description.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descriptionFocusLost(evt);
            }
        });
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 242, 251, -1));

        activate.setBackground(new java.awt.Color(153, 153, 153));
        activate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "YES", "NO" }));
        activate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateActionPerformed(evt);
            }
        });
        getContentPane().add(activate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 279, 251, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 341, 549, -1));

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 381, -1, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close2.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 381, -1, -1));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 381, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 341, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/product-50.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 15, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HD-Blur-Pictures.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select max(pid) from product");
            if(rs.first()) //if Product id exist in the table
            {
                int idd = rs.getInt(1);
                idd=idd+1;
                String str1 = String.valueOf(idd);
                id.setText(str1);
            }
            else // table is empty
            {
                id.setText("1");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void activateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activateActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        if(name.getText().equals("Enter Product name..."))
        {
            name.setText("");
            name.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        if(name.getText().equals(""))
        {
            name.setText("Enter Product name...");
            name.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_nameFocusLost

    private void rateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateFocusGained
        if(rate.getText().equals("Enter the price..."))
        {
            rate.setText("");
            rate.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_rateFocusGained

    private void rateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateFocusLost
        if(rate.getText().equals(""))
        {
            rate.setText("Enter the price...");
            rate.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_rateFocusLost

    private void descriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptionFocusGained
        if(description.getText().equals("Add description..."))
        {
            description.setText("");
            description.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_descriptionFocusGained

    private void descriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptionFocusLost
        if(description.getText().equals(""))
        {
            description.setText("Add description...");
            description.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_descriptionFocusLost

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String pid = id.getText();
        String pName = name.getText();
        String pRate = rate.getText();
        String pDescription = description.getText();
        String pActivate = (String)activate.getSelectedItem();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into product values('"+pid+"','"+pName+"','"+pRate+"','"+pDescription+"','"+pActivate+"')");
            JOptionPane.showMessageDialog(null, "Insertion Successfull.");
            setVisible(false);
            new newProduct().setVisible(true);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        setVisible(false);
        new newProduct().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Activate;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Rate;
    private javax.swing.JComboBox<String> activate;
    private javax.swing.JButton close;
    private javax.swing.JTextField description;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField rate;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
